server:
  port: ${PORT}

logging:
  level:
    com.github.vendigo.musicfriends: info

spring:
  neo4j:
    uri: bolt://${NEO4J_URL}:7687
    authentication:
      username: ${NEO4J_LOGIN}
      password: ${NEO4J_PASSWORD}
  profiles:
    active: ${BOT_MODE}

telegram.bot:
  username: music_friends_bot
  token: ${BOT_TOKEN}
  path: ${WEBHOOK_PATH}

usage.day.limit: 100
usage.day.notify: 3

messages:
  greeting: "–ü—Ä–∏–≤—ñ—Ç %s. –¢–æ–±—ñ —Ü—ñ–∫–∞–≤–æ, —è–∫–∏–π –∑–≤'—è–∑–æ–∫ –º—ñ–∂ –¥–≤–æ–º–∞, –∑–æ–≤—Å—ñ–º —Ä—ñ–∑–Ω–∏–º–∏ –∞—Ä—Ç–∏—Å—Ç–∞–º–∏? –ù—É –Ω–∞–ø—Ä–∏–∫–ª–∞–¥ –º—ñ–∂ Skofka —Ç–∞ Eminem? –ê–±–æ –ü–∞–≤–ª–æ –ó—ñ–±—Ä–æ–≤ —Ç–∞ Billie Eilish. –ì–∞–π–¥–∞ –¥—ñ–∑–Ω–∞—î–º–æ—Å—è!"
  setFirstArtist: "–û–±—Ä–∞—Ç–∏ –ø–µ—Ä—à–æ–≥–æ –∞—Ä—Ç–∏—Å—Ç–∞"
  setSecondArtist: "–û–±—Ä–∞—Ç–∏ –¥—Ä—É–≥–æ–≥–æ –∞—Ä—Ç–∏—Å—Ç–∞"
  chosenArtist: "–û–±—Ä–∞–Ω–∏–π –∞—Ä—Ç–∏—Å—Ç: "
  unknownCommand: "–ù–µ–≤—ñ–¥–æ–º–∞ –∫–æ–º–∞–Ω–¥–∞"
  tryAgain: "–°–ø—Ä–æ–±—É–≤–∞—Ç–∏ —â–µ —Ä–∞–∑"
  pathNotFound: "–®–ª—è—Ö –Ω–µ –∑–Ω–∞–π–¥–µ–Ω–∏–π"
  usageLimitReached: "–î–æ—Å—è–≥–Ω—É—Ç–æ –ª—ñ–º—ñ—Ç –≤–∏–∫–æ—Ä–∏—Å—Ç–∞–Ω–Ω—è –Ω–∞ –¥–µ–Ω—å. –ü–æ–≤–µ—Ä—Ç–∞–π—Ç–µ—Å—è –∑–∞–≤—Ç—Ä–∞."
  likeMe: "–°—Ö–æ–∂–µ, —â–æ —è –ø—Ä–∏–ø–∞–≤ —Ç–æ–±—ñ –¥–æ–≤–ø–æ–¥–æ–±–∏ üòÄ. –Ø–∫—â–æ —î –±–∞–∂–∞–Ω–Ω—è, –º–æ–∂–µ—à –∑–∞–¥–æ–Ω–∞—Ç–∏—Ç–∏ –º–µ–Ω—ñ –Ω–∞ –±–∞–Ω–∫—É: https://send.monobank.ua/jar/AeBTagsVMX\n–í—Å—ñ –≥—Ä–æ—à—ñ –ø—ñ–¥—É—Ç—å –Ω–∞ –ø—ñ–¥—Ç—Ä–∏–º–∫—É –ó–°–£. 
  –ê —è–∫—â–æ —Ö–æ—á–µ—à –¥—ñ–∑–Ω–∞—Ç–∏—Å—è, —è–∫ –∑—Ä–æ–±–∏—Ç–∏ —Ç–∞–∫–æ–≥–æ –±–æ—Ç–∞, –ø—Ä–∏—î–¥–Ω—É–π—Å—è: https://t.me/+HaC7IklWV-liMmQy"
  usefulLinks: "–ë–∞–Ω–∫–∞: https://send.monobank.ua/jar/AeBTagsVMX\nTelegram –∫–∞–Ω–∞–ª: https://t.me/+HaC7IklWV-liMmQy"
